feat(node): support unavailable node handling
ooliver1/mafic pull request #98
Opened 2023-07-25 07:35 UTC by penggin

## Summary

Add `on_node_unavailable` that is dispatched when `Node.available` become `False`.
Change `NodePool.nodes` returns only nodes that are available.
Fix doesn't wait for ready in `Node.connect` when reconnect to node.

## Checklist

- [x] If code changes were made then they have been tested.
- [x] I have run `task lint` to format code and my changes.
- [x] I have run `task pyright` and fixed the relevant issues.

2023-08-14 23:20 UTC, ooliver1 requested changes
Could the event be documented?

2023-08-26 11:06 UTC, penggin commented
Sorry for late response!
While making these changes, I found 'node_ready' event, and it's also not documented.
Will I add this, too?

2023-08-26 11:10 UTC, ooliver1 commented
Yeah sure!

2023-09-30 09:15 UTC, atomic-junky commented
Can this changes be merge ?

2023-12-18 21:16 UTC, ooliver1 approved these changes

2023-12-18 21:16 UTC, merged